### ISSUE TITLE
Downloading .bin file while visiting HTTPS Websites

### ISSUE THREAD

**Issue by Nibba2018** [j31d0/proxy2#1]
A .bin file is automatically downloaded when visiting HTTPS websites through proxy.
I have attached the .txt version of it.
[K29yKnop.txt](https://github.com/j31d0/proxy2/files/3807290/K29yKnop.txt)

**Comment by Nibba2018** [comment]
https://github.com/Nibba2018/proxy2

Here's the code that I am running...

**Comment by j31d0** [comment]
In your code, SSL socket is created without proper certificate key (I think cert_key is None at L103, https://github.com/Nibba2018/proxy2/blob/master/proxy2.py#L103), and It is different version of my code so I cannot fix it.
